version: '3'

services:
    wordpress:
        image: wordpress:php7.4
        volumes:
            - ./:/var/www/html/wp-content/themes/reference
        ports:
            - 8080:80
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DEBUG: 1
            WORDPRESS_CONFIG_EXTRA: |
                define( 'WP_DEBUG_LOG', true );
        links:
            - mysql
    mysql:
        image: mysql:5.7
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
            MYSQL_ROOT_PASSWORD: wordpress
