name: Continuous Integration/Delivery
on:
    push:
        tags:
            - '*'
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
        branches:
            - master
jobs:
    lint:
        name: Lint Project
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Cache Composer Dependencies
              id: composer-cache
              uses: actions/cache@v2
              with:
                  path: vendor/
                  key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}
            - if: steps.composer-cache.outputs.cache-hit != 'true'
              uses: php-actions/composer@v6
              with:
                  php_version: 7.4
                  command: install
            - uses: php-actions/composer@v6
              with:
                  php_version: 7.4
                  command: lint
    analyze:
        name: Analyze Project
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Cache Composer Dependencies
              id: composer-cache
              uses: actions/cache@v2
              with:
                  path: vendor/
                  key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}
            - if: steps.composer-cache.outputs.cache-hit != 'true'
              uses: php-actions/composer@v6
              with:
                  php_version: 7.4
                  command: install
            - uses: php-actions/composer@v6
              with:
                  php_version: 7.4
                  command: analyze
    package:
        if: startsWith(github.ref, 'refs/tags/')
        name: Package Theme
        needs:
            - lint
            - analyze
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Create version tag
              run: |
                version=${GITHUB_REF}
                version=${version#refs/*/}
                version=${version,,}
                version=${version//\//-}
                echo VERSION=${version} >> ${GITHUB_ENV}
            - uses: php-actions/composer@v6
              with:
                  php_version: 7.4
                  command: install
                  dev: no
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
            - run: npm install
            - run: npm run build
            - run: >
                zip -r reference-${{ env.VERSION }}.zip
                style.css
                *.php
                src/
                resources/{fonts,templates}/
                assets/
                vendor/
                languages/
            - uses: actions/upload-artifact@v2
              with:
                  name: reference-${{ env.VERSION }}
                  path: reference-${{ env.VERSION }}.zip
    deploy:
        if: startsWith(github.ref, 'refs/tags/')
        name: Deploy
        needs: package
        runs-on: ubuntu-latest
        steps:
            - name: Create version tag
              run: |
                version=${GITHUB_REF}
                version=${version#refs/*/}
                version=${version,,}
                version=${version//\//-}
                echo VERSION=${version} >> ${GITHUB_ENV}
            - uses: actions/download-artifact@v2
              with:
                  name: reference-${{ env.VERSION }}
            - run: unzip reference-${{ env.VERSION }} -d reference/
            - name: Sync
              uses: AEnterprise/rsync-deploy@v1.0
              env:
                  ARGS: -avzr --delete
                  FOLDER: reference/
                  SERVER_IP: ${{ secrets.REMOTE_HOST }}
                  SERVER_PORT: ${{ secrets.REMOTE_PORT }}
                  USERNAME: ${{ secrets.REMOTE_USER }}
                  DEPLOY_KEY: ${{ secrets.REMOTE_KEY }}
                  SERVER_DESTINATION: ${{ secrets.REMOTE_PATH }}
